---
- name: Install packages
  package:
    name: "{{ webserver_packages }}"
    state: latest

- name: Clone git repository
  git:
    repo: "{{ repository }}"
    dest: "{{ root }}"
    force: yes

# Alternative option to git cloning, used in development and kept for illustrative purposes
#- name: Copy website files from local storage to the server's document root
#  copy:
#    src: "{{ root_local }}"
#    dest: "{{ root }}"
#    mode: preserve

- name: Update cache
  apt:
    update_cache: yes

- name: Apply NGINX template
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload NGINX

- name: Enable new site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload NGINX
